MONGODB_HOST: mongodb.jrdaws.life
REDIS_HOST: redis.jrdaws.life
CATALOGUE_HOST: catalogue.jrdaws.life
CART_HOST: cart.jrdaws.life
MYSQL_HOST: mysql.jrdaws.life
USER_HOST: user.jrdaws.life
RABBITMQ_HOST: rabbitmq.jrdaws.life
SHIPPING_HOST: shipping.jrdaws.life
PAYMENT_HOST: payment.jrdaws.life