[mongodb]
localhost

[redis]
redis.jrdaws.life

[rabbitmq]
rabbitmq.jrdaws.life

[mysql]
mysql.jrdaws.life

[catalogue]
catalogue.jrdaws.life

[cart]
cart.jrdaws.life

[user]
user.jrdaws.life

[frontend]
frontend.jrdaws.life

[payment]
payment.jrdaws.life

[shipping]
shipping.jrdaws.life



[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory